import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "webXProj.settings")
django.setup()

from interviewprep.models import Question

print("\n🗑 Clearing old questions...")
Question.objects.all().delete()
print("✔ Cleared successfully!\n")

data = [

# ================= FRONTEND ==================
# HTML (20)
("Frontend", "HTML", "Which HTML tag is used to create a hyperlink?", ["<a>", "<link>", "<url>", "<href>"], "A"),
("Frontend", "HTML", "Which tag defines the largest heading?", ["<h6>", "<header>", "<h1>", "<head>"], "C"),
("Frontend", "HTML", "Which tag is used for inserting an image?", ["<img>", "<src>", "<image>", "<pic>"], "A"),
("Frontend", "HTML", "Which attribute gives alternative text to images?", ["title", "src", "alt", "href"], "C"),
("Frontend", "HTML", "Which tag is used for input fields?", ["<input>", "<form>", "<textfield>", "<text>"], "A"),
("Frontend", "HTML", "Which element contains metadata?", ["<body>", "<meta>", "<head>", "<script>"], "C"),
("Frontend", "HTML", "Which tag creates a dropdown?", ["<select>", "<dropdown>", "<list>", "<input>"], "A"),
("Frontend", "HTML", "HTML stands for?", ["Hyper Trainer Marking Language", "HyperText Markup Language", "HyperText Markdown Language", "None"], "B"),
("Frontend", "HTML", "Which tag is used for lists?", ["<ul>", "<p>", "<h1>", "<table>"], "A"),
("Frontend", "HTML", "To make text bold:", ["<b>", "<strong>", "<p>", "Both A & B"], "D"),
("Frontend", "HTML", "Which tag defines a table row?", ["<td>", "<tr>", "<th>", "<table>"], "B"),
("Frontend", "HTML", "Which tag defines a form?", ["<form>", "<input>", "<body>", "<div>"], "A"),
("Frontend", "HTML", "Which tag embeds a video?", ["<video>", "<movie>", "<media>", "<play>"], "A"),
("Frontend", "HTML", "Which element defines navigation links?", ["<nav>", "<header>", "<footer>", "<menu>"], "A"),
("Frontend", "HTML", "Which is a block-level element?", ["<span>", "<div>", "<b>", "<i>"], "B"),
("Frontend", "HTML", "Which tag forces a new line?", ["<span>", "<hr>", "<br>", "<p>"], "C"),
("Frontend", "HTML", "The root element of an HTML page:", ["<html>", "<DOCTYPE>", "<body>", "<title>"], "A"),
("Frontend", "HTML", "Which tag is self-closing?", ["<img>", "<div>", "<p>", "<table>"], "A"),
("Frontend", "HTML", "Input type for password?", ["text", "password", "secure", "code"], "B"),
("Frontend", "HTML", "Semantic tag:", ["<div>", "<span>", "<article>", "<b>"], "C"),

# CSS (20)
("Frontend", "CSS", "CSS stands for?", ["Cascade Style Sheets", "Cascading Style Sheets", "Color Style Syntax", "Code Styling System"], "B"),
("Frontend", "CSS", "Which property changes text color?", ["font-color", "color", "text-style", "bgcolor"], "B"),
("Frontend", "CSS", "Which unit is relative to root font size?", ["em", "px", "rem", "%"], "C"),
("Frontend", "CSS", "Which creates a flex container?", ["display:flex", "flex:true", "position:flex", "flexbox"], "A"),
("Frontend", "CSS", "Which property sets the background color?", ["background-color", "bgcolor", "color", "background-style"], "A"),
("Frontend", "CSS", "Which CSS uses ID selector?", ["#", ".", ":", "*"], "A"),
("Frontend", "CSS", "Which property sets the font size?", ["text-size", "font-size", "size", "fontsize"], "B"),
("Frontend", "CSS", "How do you make text bold?", ["font-style:bold", "font-weight:bold", "text:bold", "bold:true"], "B"),
("Frontend", "CSS", "Which property adds space inside the element?", ["margin", "padding", "border", "gap"], "B"),
("Frontend", "CSS", "Which property is used for rounded corners?", ["corner-radius", "border-radius", "round-corner", "shape-radius"], "B"),
("Frontend", "CSS", "Default position property value?", ["fixed", "absolute", "relative", "static"], "D"),
("Frontend", "CSS", "Which property controls the stacking order?", ["index", "z-index", "stack", "order"], "B"),
("Frontend", "CSS", "Which display type hides the element but reserves its space?", ["display:none", "visibility:hidden", "opacity:0", "hidden:true"], "B"),
("Frontend", "CSS", "How to set a background image?", ["background:url(image)", "image:url()", "bg-image:()", "background-img()"], "A"),
("Frontend", "CSS", "Which property aligns text horizontally?", ["align", "justify", "text-align", "text-position"], "C"),
("Frontend", "CSS", "Which unit is relative to parent font size?", ["px", "em", "rem", "pt"], "B"),
("Frontend", "CSS", "Which property makes content scrollable?", ["scroll", "overflow", "slide", "scrolling"], "B"),
("Frontend", "CSS", "Which one selects all paragraph tags?", ["#p", ".p", "p", "*p"], "C"),
("Frontend", "CSS", "CSS flex-direction default value?", ["row", "column", "reverse", "flex"], "A"),
("Frontend", "CSS", "Which selector targets immediate child elements?", ["A B", "A > B", "A + B", "A ~ B"], "B"),

# ================= JS (20)
("Frontend", "JS", "Which keyword declares a block-scoped variable?", ["var", "let", "const", "static"], "B"),
("Frontend", "JS", "Which method converts JSON to JavaScript object?", ["JSON.stringify()", "JSON.parse()", "parse.JSON()", "Object.parse()"], "B"),
("Frontend", "JS", "Which symbol is used for strict equality check?", ["==", "===", "!=", "="], "B"),
("Frontend", "JS", "What is the output type of typeof null?", ["object", "null", "undefined", "boolean"], "A"),
("Frontend", "JS", "Which function is used to delay execution?", ["setInterval()", "setTimeout()", "wait()", "delay()"], "B"),
("Frontend", "JS", "How to write a comment in JavaScript?", ["<!--comment-->", "* comment *", "# comment", "// comment"], "D"),
("Frontend", "JS", "Which of the following is not a JS data type?", ["String", "Boolean", "Float", "Object"], "C"),
("Frontend", "JS", "Which built-in method removes last element of array?", ["shift()", "pop()", "remove()", "delete"], "B"),
("Frontend", "JS", "Which operator spreads array elements?", ["...", "??", "+", "**"], "A"),
("Frontend", "JS", "Which method selects element by ID?", ["getElementsByClass", "querySelectorAll()", "getElementById()", "$()"], "C"),
("Frontend", "JS", "Which object handles browser alerts?", ["console", "window", "document", "navigator"], "B"),
("Frontend", "JS", "Which array method returns new filtered array?", ["map()", "filter()", "sort()", "slice()"], "B"),
("Frontend", "JS", "Which keyword stops loop execution?", ["break", "stop", "halt", "end"], "A"),
("Frontend", "JS", "Which of these defines a function?", ["func my()", "function my()", "define my()", "method my()"], "B"),
("Frontend", "JS", "Which method adds an element to end of array?", ["push()", "add()", "insert()", "append()"], "A"),
("Frontend", "JS", "What is NaN?", ["Not a Number", "No use", "Null as Number", "Negative Array Number"], "A"),
("Frontend", "JS", "Which method converts string to integer?", ["parseInt()", "int()", "strToInt()", "stringToNumber()"], "A"),
("Frontend", "JS", "Promises represent?", ["Errors only", "Data only", "Future value", "Loop"], "C"),
("Frontend", "JS", "Arrow functions were introduced in?", ["ES4", "ES5", "ES6", "ES7"], "C"),
("Frontend", "JS", "LocalStorage stores data for?", ["Page session only", "Until manually cleared", "Only 24 hours", "Only in RAM"], "B"),

# ================= React (20)
("Frontend", "React", "What is React mainly used for?", ["Database", "Styling", "Building UI", "Security"], "C"),
("Frontend", "React", "JSX stands for?", ["JavaScript XML", "Java Syntax Extension", "JSON XML", "None"], "A"),
("Frontend", "React", "Which hook manages state?", ["useState()", "useEffect()", "useMemo()", "useRef()"], "A"),
("Frontend", "React", "Which helps handling side-effects?", ["useContext()", "useEffect()", "useReducer()", "useDebug()"], "B"),
("Frontend", "React", "What is Virtual DOM?", ["Copy of HTML DOM in memory", "Real DOM", "Database tree", "CSS Renderer"], "A"),
("Frontend", "React", "Props are?", ["Mutable", "Read-only", "Not required", "Functions"], "B"),
("Frontend", "React", "Which command creates a new React app?", ["react new", "create-react-app", "npm react", "react-create"], "B"),
("Frontend", "React", "Which hook replaces lifecycle methods?", ["useRef()", "useState()", "useEffect()", "useCallback()"], "C"),
("Frontend", "React", "Which hook is used for global state & data sharing?", ["useShare()", "useContext()", "useGlobal()", "useProp()"], "B"),
("Frontend", "React", "Default file extension for JSX?", [".js", ".jsx", ".html", ".tsx"], "B"),
("Frontend", "React", "Keys in lists help?", ["Uniqueness & diffing", "Sorting", "CSS styling", "Debugging"], "A"),
("Frontend", "React", "In React, data flows?", ["Both ways", "Two-way binding", "One-way downward", "Random"], "C"),
("Frontend", "React", "Which file represents entry point in CRA?", ["app.js", "index.js", "main.js", "home.js"], "B"),
("Frontend", "React", "Which renders UI in browser?", ["ReactDOM.render()", "Renderer()", "UI.create()", "React.render()"], "A"),
("Frontend", "React", "Which hook stores mutable DOM ref?", ["useState()", "useRef()", "useMemo()", "useDOM()"], "B"),
("Frontend", "React", "React is based on?", ["MVC", "OOP", "Component-based architecture", "None"], "C"),
("Frontend", "React", "State updates are?", ["Synchronous", "Asynchronous", "Manual only", "Not allowed"], "B"),
("Frontend", "React", "React Router enables?", ["Animations", "Database", "Page navigation", "Hooks"], "C"),
("Frontend", "React", "Fragments are created using?", ["<div>", "<frag>", "<Fragment>", "<>...</>"], "D"),
("Frontend", "React", "Which hook optimizes expensive calculations?", ["useMemo()", "useEffect()", "useReducer()", "useError()"], "A"),

# ================= BACKEND ==================

# 🐍 PYTHON (20)
("Backend", "Python", "Which keyword is used to create a function in Python?", ["func", "define", "function", "def"], "D"),
("Backend", "Python", "Which is a valid data type in Python?", ["integer", "decimal", "char", "word"], "A"),
("Backend", "Python", "What does PEP stand for?", ["Python Enhancement Proposal", "Python Enterprise Planning", "Performance Enhancement Plan", "Program Execution Promise"], "A"),
("Backend", "Python", "Which collection is ordered and immutable?", ["List", "Tuple", "Set", "Dictionary"], "B"),
("Backend", "Python", "Which keyword is used to handle exceptions?", ["catch", "try", "except", "throw"], "C"),
("Backend", "Python", "What is the output of len('Python')?", ["5", "6", "7", "None"], "B"),
("Backend", "Python", "Which operator is used for exponent?", ["^", "exp", "**", "^^"], "C"),
("Backend", "Python", "What is the default value of variable not assigned?", ["null", "undefined", "None", "empty"], "C"),
("Backend", "Python", "What is list indexing start value?", ["0", "1", "-1", "None"], "A"),
("Backend", "Python", "Which keyword deletes an object?", ["remove", "delete", "del", "destroy"], "C"),
("Backend", "Python", "pip is used for?", ["package installation", "compilation", "debugging", "deploying"], "A"),
("Backend", "Python", "Which is used to define a class?", ["class", "object", "cls", "model"], "A"),
("Backend", "Python", "Lambda functions are?", ["Named", "Anonymous", "Recursive only", "Class-only"], "B"),
("Backend", "Python", "Which method converts string to integer?", ["parseInt()", "int()", "toInt()", "convert()"], "B"),
("Backend", "Python", "Which loop repeats a known number of times?", ["while", "for", "loop", "repeat"], "B"),
("Backend", "Python", "Which module is used for JSON?", ["java", "json", "dict", "pyjson"], "B"),
("Backend", "Python", "Dictionaries store data as?", ["key-value pairs", "values only", "keys only", "indexed pairs"], "A"),
("Backend", "Python", "What is the file extension of Python?", [".py", ".pp", ".pys", ".px"], "A"),
("Backend", "Python", "Which converts a list into a set?", ["list()", "set()", "tuple()", "dict()"], "B"),
("Backend", "Python", "Break is used to?", ["Stop entire loop", "Pause loop", "Skip loop", "Restart loop"], "A"),


# 🏗 DJANGO (20)
("Backend", "Django", "Django is written in?", ["Java", "Python", "C", "Rust"], "B"),
("Backend", "Django", "Django follows which architecture?", ["MVC", "MVVM", "MVT", "MVP"], "C"),
("Backend", "Django", "Which file contains URL patterns?", ["models.py", "urls.py", "views.py", "settings.py"], "B"),
("Backend", "Django", "Which command starts a Django project?", ["django-admin create", "django startproject", "django-admin startproject", "start django"], "C"),
("Backend", "Django", "Which command creates a new app?", ["django-admin startapp", "django makeapp", "django appstart", "python createapp"], "A"),
("Backend", "Django", "Which ORM does Django use?", ["Hibernate", "Django ORM", "SQLAlchemy", "ODBC"], "B"),
("Backend", "Django", "Which template engine is default in Django?", ["Jinja", "Mako", "Django Template Language", "React"], "C"),
("Backend", "Django", "Which file stores DB settings?", ["admin.py", "urls.py", "settings.py", "views.py"], "C"),
("Backend", "Django", "manage.py is used for?", ["Server automation", "Administrative tasks", "HTML rendering", "Testing only"], "B"),
("Backend", "Django", "Which command runs development server?", ["runserver", "serve", "start", "run"], "A"),
("Backend", "Django", "Which is used for DB migration?", ["makemigrations", "db migrate", "sync", "create"], "A"),
("Backend", "Django", "Which converts models to DB schema?", ["migrate", "makedb", "runschema", "createDB"], "A"),
("Backend", "Django", "Where are database models defined?", ["models.py", "db.py", "views.py", "admin.py"], "A"),
("Backend", "Django", "Which module registers models in admin panel?", ["admin.py", "urls.py", "forms.py", "settings.py"], "A"),
("Backend", "Django", "Which response is JSON response?", ["HttpResponse", "JsonResponse", "WebResponse", "Response"], "B"),
("Backend", "Django", "CSRF stands for?", ["Cross Site Request Forgery", "Client Secure Request Form", "Central Security Role Form", "Cross Site Resource Form"], "A"),
("Backend", "Django", "Which decorator restricts access to logged-in users?", ["@private", "@login_required", "@authenticated", "@restrict"], "B"),
("Backend", "Django", "Static files are stored in?", ["static/", "media/", "assets/", "public/"], "A"),
("Backend", "Django", "Templates folder stores?", ["CSS", "HTML", "Python Scripts", "DB"], "B"),
("Backend", "Django", "REST Framework is used to build?", ["WebSockets", "APIs", "Animations", "Admin UI"], "B"),


# 🌐 NODE.JS (20)
("Backend", "Node.js", "Node.js is built on which engine?", ["V8 engine", "SpiderMonkey", "Chakra", "Nashorn"], "A"),
("Backend", "Node.js", "Node.js mainly uses?", ["Multithreading", "Single-threaded event loop", "Compiler threads", "Mainframe"], "B"),
("Backend", "Node.js", "Which statement is true?", ["Node.js is frontend", "Node.js is backend", "Node.js is OS", "Node.js is database"], "B"),
("Backend", "Node.js", "Which module handles file operations?", ["http", "fs", "url", "os"], "B"),
("Backend", "Node.js", "Which command initializes a project?", ["node init", "npm init", "npm start", "node new"], "B"),
("Backend", "Node.js", "Package manager used in Node?", ["pip", "yarn", "npm", "gradle"], "C"),
("Backend", "Node.js", "Which method creates a server?", ["http.createServer()", "server()", "new http()", "http.make()"], "A"),
("Backend", "Node.js", "Which module creates routes?", ["os", "router", "path", "express"], "D"),
("Backend", "Node.js", "Which extension is Node file?", [".js", ".node", ".txt", ".npm"], "A"),
("Backend", "Node.js", "Which reads environment variables?", ["env()", "process.env", "getENV()", "read.env"], "B"),
("Backend", "Node.js", "To install a package globally:", ["npm i -g package", "npm g install", "install -g", "npm global"], "A"),
("Backend", "Node.js", "Which parses URL?", ["query", "url.parse()", "fs.parse()", "router.url()"], "B"),
("Backend", "Node.js", "Express is used for?", ["File handling", "Database", "Web server", "Testing"], "C"),
("Backend", "Node.js", "Which is NoSQL DB often used with Node?", ["MySQL", "MongoDB", "SQLite", "PostgreSQL"], "B"),
("Backend", "Node.js", "Node package file name?", ["package.json", "app.json", "nodefile.json", "modules.json"], "A"),
("Backend", "Node.js", "Which is async?", ["fs.readFile()", "while loop", "Math.max()", "JSON.stringify()"], "A"),
("Backend", "Node.js", "How to start Node REPL?", ["node start", "node", "npm run", "repl"], "B"),
("Backend", "Node.js", "Which function terminates script?", ["kill()", "exit()", "stop()", "halt()"], "B"),
("Backend", "Node.js", "Middleware in Express are?", ["Request handlers", "DB models", "Templates", "Static pages"], "A"),
("Backend", "Node.js", "Socket.io is used for?", ["File upload", "Real-time communication", "Testing", "Web scraping"], "B"),


# ================= DATABASE ==================
# SQL (20)
("Database", "SQL", "SQL stands for?", ["Structured Query Language", "Simple Query Language", "Server Query Language", "Syntax Query Language"], "A"),
("Database", "SQL", "Which keyword retrieves data?", ["INSERT", "SELECT", "DELETE", "UPDATE"], "B"),
("Database", "SQL", "Which clause filters records?", ["WHERE", "FROM", "ORDER BY", "GROUP BY"], "A"),
("Database", "SQL", "Primary key must be?", ["Unique", "Nullable", "Duplicate", "Both A & B"], "A"),
("Database", "SQL", "Which removes duplicate values?", ["UNIQUE", "DISTINCT", "FILTER", "REMOVE"], "B"),
("Database", "SQL", "Default sort order of ORDER BY?", ["Ascending", "Descending", "Random", "None"], "A"),
("Database", "SQL", "Which operator is pattern matching?", ["LIKE", "MATCH", "IN", "BETWEEN"], "A"),
("Database", "SQL", "To remove a table completely:", ["DROP", "DELETE", "REMOVE", "CLEAR"], "A"),
("Database", "SQL", "Which constraint ensures referential integrity?", ["CHECK", "FOREIGN KEY", "INDEX", "DEFAULT"], "B"),
("Database", "SQL", "Aggregate function?", ["COUNT()", "WHERE", "ORDER BY", "JOIN"], "A"),
("Database", "SQL", "INNER JOIN returns?", ["Unmatched rows only", "Matched rows only", "All rows", "None"], "B"),
("Database", "SQL", "Which statement adds data?", ["INSERT", "SELECT", "ALTER", "UPDATE"], "A"),
("Database", "SQL", "Which groups row values?", ["GROUP BY", "ORDER BY", "WHERE", "FILTER"], "A"),
("Database", "SQL", "Wildcard for single character in LIKE?", ["_", "%", "*", "#"], "A"),
("Database", "SQL", "Which combines result of two SELECTs?", ["JOIN", "UNION", "MERGE", "APPEND"], "B"),
("Database", "SQL", "Which is NOT DML?", ["SELECT", "UPDATE", "DELETE", "CREATE"], "D"),
("Database", "SQL", "NULL means?", ["Zero", "Empty string", "Unknown value", "False"], "C"),
("Database", "SQL", "To rename a table:", ["MODIFY", "ALTER", "RENAME", "CHANGE"], "C"),
("Database", "SQL", "Which locks structure of table?", ["DML", "DDL", "DCL", "TCL"], "B"),
("Database", "SQL", "Default transaction control command?", ["COMMIT", "UNDO", "SAVE", "ROLLBACK"], "A"),


# MongoDB (20)
("Database", "MongoDB", "MongoDB is a?", ["Relational DB", "Document DB", "Key-Value store", "File DB"], "B"),
("Database", "MongoDB", "Default MongoDB database?", ["test", "admin", "config", "default"], "A"),
("Database", "MongoDB", "MongoDB stores data in?", ["Tables", "Collections", "Rows", "Fields"], "B"),
("Database", "MongoDB", "Mongo shell command to show DBs?", ["SHOW DBS", "show databases", "db.show()", "display"], "B"),
("Database", "MongoDB", "File format for storage:", ["XML", "BSON", "CSV", "SQL"], "B"),
("Database", "MongoDB", "Equivalent of row in MongoDB?", ["Tuple", "Document", "Field", "Schema"], "B"),
("Database", "MongoDB", "_id field is?", ["Nullable", "Auto-generated", "Duplicate allowed", "Removed"], "B"),
("Database", "MongoDB", "Index creation command:", ["db.index()", "db.collection.createIndex()", "db.addIndex()", "create.index()"], "B"),
("Database", "MongoDB", "Which operator selects values greater than?", ["$lt", "$gt", "$eq", "$gte"], "B"),
("Database", "MongoDB", "NoSQL stands for?", ["Non SQL", "Not Only SQL", "New SQL", "None"], "B"),
("Database", "MongoDB", "Command to insert single doc:", ["insertOne()", "insert()", "insertDoc()", "addOne()"], "A"),
("Database", "MongoDB", "Command to update document:", ["updateDoc()", "updateOne()", "set()", "save()"], "B"),
("Database", "MongoDB", "Which command deletes many docs?", ["delete()", "remove()", "deleteMany()", "drop()"], "C"),
("Database", "MongoDB", "Aggregation uses?", ["SQL Server", "Pipeline", "Triggers", "Indexes"], "B"),
("Database", "MongoDB", "Which replicates data?", ["Sharding", "Journaling", "Replication", "Backup"], "C"),
("Database", "MongoDB", "MongoDB is best for?", ["Complex joins", "Distributed scalable apps", "Batch reports", "None"], "B"),
("Database", "MongoDB", "To drop collection:", ["db.drop()", "db.collection.drop()", "drop.collection()", "removeAll()"], "B"),
("Database", "MongoDB", "MongoDB uses?", ["Schema first", "Schema-on-write", "Schema-less", "Strict schema"], "C"),
("Database", "MongoDB", "Which operator checks existence?", ["$exists", "$in", "$eq", "$valid"], "A"),
("Database", "MongoDB", "To backup database:", ["mongodump", "mongodb-backup", "backup()", "mongoexport-only"], "A"),


# LOGICAL REASONING (20)
("Aptitude", "Logical", "Find the next number: 2, 6, 12, 20, ?", ["28", "30", "32", "34"], "C"),
("Aptitude", "Logical", "Which is the odd one out?", ["Dog", "Cat", "Wolf", "Cow"], "D"),
("Aptitude", "Logical", "If A=1, B=2,..., Z=26, then J+K?", ["20", "21", "25", "27"], "A"),
("Aptitude", "Logical", "Which completes: AB, CD, EF, GH, ?", ["HI", "IJ", "JK", "KL"], "B"),
("Aptitude", "Logical", "Opposite of South-West?", ["North-West", "South-East", "North-East", "East"], "C"),
("Aptitude", "Logical", "Clock: Minutes :: Calendar: ?", ["Days", "Weeks", "Months", "Years"], "A"),
("Aptitude", "Logical", "Which is heavier?", ["1 kg cotton", "1 kg iron", "Both same", "Cotton"], "C"),
("Aptitude", "Logical", "Cube has how many edges?", ["8", "12", "6", "10"], "B"),
("Aptitude", "Logical", "Blood relation: Brother’s father?", ["Uncle", "Cousin", "Father", "Son"], "C"),
("Aptitude", "Logical", "What comes next? Z, X, V, T, ?", ["R", "S", "Q", "P"], "A"),
("Aptitude", "Logical", "Odd one: Red, Blue, Pink, Yellow", ["Red", "Blue", "Pink", "Yellow"], "C"),
("Aptitude", "Logical", "If 5x=20, x=?", ["2", "3", "4", "5"], "C"),
("Aptitude", "Logical", "Shape with 5 sides?", ["Pentagon", "Hexagon", "Heptagon", "Square"], "A"),
("Aptitude", "Logical", "Opposite of narrow?", ["Wide", "Thin", "Broad", "Both A & C"], "D"),
("Aptitude", "Logical", "IQ stands for?", ["Intelligence Quotient", "Idea Quality", "Impact Quotient", "None"], "A"),
("Aptitude", "Logical", "Which is not a mammal?", ["Whale", "Dolphin", "Shark", "Elephant"], "C"),
("Aptitude", "Logical", "Mirror image flips:", ["Right to left", "Left to right", "Top to bottom", "Both A & B"], "D"),
("Aptitude", "Logical", "Triangle has:", ["2 angles", "3 angles", "4 angles", "5 angles"], "B"),
("Aptitude", "Logical", "Find missing: 9, 16, ?, 36", ["20", "24", "25", "30"], "C"),
("Aptitude", "Logical", "Fast : Slow :: Hot : ?", ["Warm", "Cold", "Cool", "Neutral"], "B"),


# REASONING (20)
("Aptitude", "Problem Solving", "If TRAIN is coded as UQBJO, code PLANE", ["QKZMD", "QMBOD", "QKZOF", "QMBPF"], "D"),
("Aptitude", "Problem Solving", "Find next: 5, 10, 20, 40, ?", ["50", "70", "80", "90"], "C"),
("Aptitude", "Problem Solving", "Which is odd one: Apple, Banana, Tomato, Mango", ["Apple", "Banana", "Tomato", "Mango"], "C"),
("Aptitude", "Problem Solving", "12 is to 144, like 9 is to?", ["91", "99", "81", "45"], "C"),
("Aptitude", "Problem Solving", "Sum of angles in triangle?", ["90°", "180°", "270°", "360°"], "B"),
("Aptitude", "Problem Solving", "Cube of 3?", ["6", "9", "27", "81"], "C"),
("Aptitude", "Problem Solving", "Solve: 8×3÷4?", ["6", "10", "2", "8"], "A"),
("Aptitude", "Problem Solving", "Which is not prime?", ["3", "5", "9", "11"], "C"),
("Aptitude", "Problem Solving", "Which day comes before Saturday?", ["Friday", "Sunday", "Monday", "Tuesday"], "A"),
("Aptitude", "Problem Solving", "√49?", ["5", "6", "7", "8"], "C"),
("Aptitude", "Problem Solving", "Which one is largest?", ["0.5", "0.2", "0.8", "0.6"], "C"),
("Aptitude", "Problem Solving", "Face opposite 1 on dice?", ["2", "3", "6", "Can't determine"], "D"),
("Aptitude", "Problem Solving", "Position of Q in alphabet?", ["16", "17", "18", "19"], "B"),
("Aptitude", "Problem Solving", "Smallest two-digit prime?", ["11", "13", "17", "19"], "A"),
("Aptitude", "Problem Solving", "15% of 200?", ["15", "20", "25", "30"], "D"),
("Aptitude", "Problem Solving", "Opposite of rich?", ["Wealthy", "Poor", "Cheap", "None"], "B"),
("Aptitude", "Problem Solving", "Even number:", ["3", "7", "9", "10"], "D"),
("Aptitude", "Problem Solving", "Blood red due to?", ["Oxygen", "Hemoglobin", "WBC", "Plasma"], "B"),
("Aptitude", "Problem Solving", "Which does not belong to family?", ["Father", "Mother", "Teacher", "Brother"], "C"),
("Aptitude", "Problem Solving", "Which is a mammal?", ["Frog", "Snake", "Bat", "Lizard"], "C"),



# QUANTITATIVE (20)
("Aptitude", "Quantitative", "√121?", ["9", "10", "11", "12"], "C"),
("Aptitude", "Quantitative", "Simple Interest = P×R×T / ?", ["100", "50", "10", "1"], "A"),
("Aptitude", "Quantitative", "Find %: 25/100 ?", ["20%", "25%", "30%", "10%"], "B"),
("Aptitude", "Quantitative", "Speed = Distance / ?", ["Mass", "Time", "Power", "Rate"], "B"),
("Aptitude", "Quantitative", "Area of rectangle?", ["2(l+w)", "l×w", "πr²", "l²"], "B"),
("Aptitude", "Quantitative", "Solve: 45÷5?", ["5", "8", "9", "10"], "C"),
("Aptitude", "Quantitative", "LCM of 4 & 6?", ["10", "12", "16", "20"], "B"),
("Aptitude", "Quantitative", "If 50% of x is 15, x=?", ["25", "30", "35", "40"], "B"),
("Aptitude", "Quantitative", "1 km = ?", ["100 m", "500 m", "1000 m", "10,000 m"], "C"),
("Aptitude", "Quantitative", "Perimeter of square = ?", ["4a", "2a", "a²", "4a²"], "A"),
("Aptitude", "Quantitative", "Solve: (6+3×2)?", ["12", "18", "24", "13"], "D"),
("Aptitude", "Quantitative", "Circumference of circle = ?", ["πr²", "2πr", "r²", "4πr"], "B"),
("Aptitude", "Quantitative", "Cube root of 27?", ["2", "3", "4", "5"], "B"),
("Aptitude", "Quantitative", "Ratio of 4:8?", ["1:2", "2:1", "4:6", "1:4"], "A"),
("Aptitude", "Quantitative", "Prime number?", ["21", "27", "29", "49"], "C"),
("Aptitude", "Quantitative", "Sum of first 10 natural numbers?", ["45", "50", "55", "60"], "C"),
("Aptitude", "Quantitative", "0.75 = ?", ["3/4", "1/2", "1/4", "2/3"], "A"),
("Aptitude", "Quantitative", "Solve: 12×12?", ["124", "134", "144", "154"], "C"),
("Aptitude", "Quantitative", "Discount = MP - ?", ["CP", "SP", "Profit", "Loss"], "B"),
("Aptitude", "Quantitative", "Volume of cube?", ["a³", "a²", "2a", "3a"], "A"),

# ================= HR ==================
("HR", "All", "Why should we hire you?", 
 ["Because I need a job", "I have skills that match this role", "I want salary", "I need experience"], "B"),
("HR", "All", "What is your biggest strength?", 
 ["Communication", "Laziness", "Procrastination", "No strength"], "A"),
("HR", "All", "Are you willing to relocate?", 
 ["No", "Maybe", "Yes", "Depends on salary"], "C"),
("HR", "All", "How do you handle stress?", 
 ["Avoid work", "Time management & calm focus", "Argue with manager", "Quit"], "B"),
("HR", "All", "What motivates you?", 
 ["Money only", "Growth and learning", "Taking leave", "Office gossip"], "B"),
("HR", "All", "Team conflict resolution involves?", 
 ["Fighting", "Communication & collaboration", "Ignoring", "Complaining"], "B"),
("HR", "All", "Where do you see yourself in 5 years?", 
 ["Same position", "Manager/Expert in role", "Jobless", "Studying again"], "B"),
("HR", "All", "Your biggest weakness?", 
 ["None", "I work too hard", "Real improvement point", "I don’t have weaknesses"], "C"),
("HR", "All", "What do you know about our company?", 
 ["Not sure", "Basic research done", "Nothing", "Competitor company"], "B"),
("HR", "All", "What makes a good team player?", 
 ["Blaming others", "Support & communication", "Avoiding team", "Being silent always"], "B"),
("HR", "All", "What if you disagree with your manager?", 
 ["Argue", "Discuss calmly & clarify", "Resign", "Ignore"], "B"),
("HR", "All", "What is your salary expectation?", 
 ["As per industry standards", "Highest package", "Lowest possible", "No answer"], "A"),
("HR", "All", "Why did you choose this career?", 
 ["Randomly", "Passion & skills match", "Friends suggested", "Salary only"], "B"),
("HR", "All", "What is work-life balance?", 
 ["Only work", "Equal importance to both", "Only life", "No meaning"], "B"),
("HR", "All", "How do you prioritize tasks?", 
 ["Randomly", "Based on urgency & importance", "Ask friend", "Ignore deadlines"], "B"),
("HR", "All", "Describe yourself in one word?", 
 ["Lazy", "Dedicated", "Angry", "Unpredictable"], "B"),
("HR", "All", "If failed in task, you will?", 
 ["Blame others", "Learn & retry", "Quit", "Cry"], "B"),
("HR", "All", "What is the best company culture?", 
 ["Toxic", "Supportive & collaborative", "No rules", "One-man control"], "B"),
("HR", "All", "Can you work under pressure?", 
 ["No", "Yes", "Sometimes", "Depends"], "B"),
("HR", "All", "Tell me about a challenge you overcame:", 
 ["Make one", "Real example with result", "Don’t answer", "Blame team"], "B"),


# ================= SYSTEM DESIGN ==================
("System Design", "Basics", "What is system design?", 
 ["Front-end only", "Designing architecture of software systems", "Testing software", "Fixing UI issues"], "B"),
("System Design", "Basics", "Load balancer helps?", 
 ["Reduce traffic", "Distribute incoming traffic", "Backup servers", "Database only"], "B"),
("System Design", "Basics", "Cache is used for?", 
 ["Slowing response", "Faster data retrieval", "Deleting data", "Security"], "B"),
("System Design", "Basics", "CDN stands for?", 
 ["Content Delivery Network", "Central Data Node", "Cloud Delivery Network", "Cyber Data Network"], "A"),
("System Design", "Basics", "Stateless protocol example?",
 ["TCP", "UDP", "HTTP", "FTP"], "C"),
("System Design", "Basics", "Horizontal scaling means?",
 ["Increasing CPU/RAM", "Adding more servers", "Replacing servers", "Shutting servers"], "B"),
("System Design", "Basics", "Database sharding improves?",
 ["Performance & scalability", "Security only", "Design only", "Coding only"], "A"),
("System Design", "Basics", "What stores request logs?",
 ["Database", "Log Storage", "RAM", "Firewall"], "B"),
("System Design", "Basics", "Which improves search performance?",
 ["Indexing", "Delete DB", "Disable Cache", "Remove table"], "A"),
("System Design", "Basics", "API Gateways manage?",
 ["Static files", "Microservices routing & auth", "Only frontend", "Hardware"], "B"),
("System Design", "Basics", "Proxy servers provide?",
 ["Security & anonymity", "Database access", "Frontend UI", "Coding"], "A"),
("System Design", "Basics", "Redundancy helps?",
 ["Delete data", "Avoid single point failure", "Reduce servers", "None"], "B"),
("System Design", "Basics", "Which improves availability?",
 ["Single server", "Distributed system", "Removing backups", "One database"], "B"),
("System Design", "Basics", "Latency refers to?",
 ["Speed", "Delay in response", "Memory", "Storage"], "B"),
("System Design", "Basics", "CAP theorem: C stands for?",
 ["Consistency", "Currency", "Caching", "Cluster"], "A"),
("System Design", "Basics", "Message queue used for?",
 ["Async communication", "UI design", "DB schema", "Testing"], "A"),
("System Design", "Basics", "Microservices architecture offers?",
 ["Monolithic structure", "Independent deployability", "Single database only", "No scaling"], "B"),
("System Design", "Basics", "Data replication used for?",
 ["Speed only", "Availability & fault tolerance", "Log writing only", "Authentication"], "B"),
("System Design", "Basics", "REST uses?",
 ["Stateful design", "Stateless design", "Binary connection", "MQTT only"], "B"),
("System Design", "Basics", "Hashing ensures?",
 ["Encryption only", "Consistent data lookup", "Compression", "SQL joins"], "B"),


# DATABASE DESIGN (20)
("System Design", "Database Design", "Normalization removes?", 
 ["Redundancy", "Indexes", "Columns", "NULLs"], "A"),
("System Design", "Database Design", "Primary purpose of ER diagram?",
 ["UI Layout", "Database structure representation", "Testing", "Deployment"], "B"),
("System Design", "Database Design", "Foreign Key ensures?",
 ["Data loss", "Referential integrity", "Speed only", "None"], "B"),
("System Design", "Database Design", "Which is 1st Normal Form?",
 ["Repeating groups allowed", "Atomic values", "Duplicate columns allowed", "No primary key"], "B"),
("System Design", "Database Design", "Unique key allows?",
 ["Duplicates only", "NULL once", "Multiple NULLs", "No indexing"], "B"),
("System Design", "Database Design", "Denormalization improves?",
 ["Performance", "Data consistency", "Redundancy removal", "None"], "A"),
("System Design", "Database Design", "Star schema used in?",
 ["OLTP", "OLAP", "Game engines", "Web UI"], "B"),
("System Design", "Database Design", "Composite key contains?",
 ["One column", "Two or more columns", "Only string values", "Temporary values"], "B"),
("System Design", "Database Design", "Index improves?",
 ["Insert only", "Read performance", "Delete speed", "Nothing"], "B"),
("System Design", "Database Design", "Which is NOT ACID property?",
 ["Atomicity", "Consistency", "Isolation", "Distribution"], "D"),
("System Design", "Database Design", "Schema defines?",
 ["Logic structure of database", "Networking", "Frontend UI", "Security"], "A"),
("System Design", "Database Design", "Which maintains history of changes?",
 ["Triggers", "Logs", "Cache", "Indexes"], "B"),
("System Design", "Database Design", "UUID used for?",
 ["Unique identifiers", "Indexes only", "Deleting data", "RAM management"], "A"),
("System Design", "Database Design", "Sharding used when?",
 ["Small DB", "Large distributed DB", "Static DB", "Temporary DB"], "B"),
("System Design", "Database Design", "Which avoids deadlocks?",
 ["Transactions", "Proper locking", "One thread only", "Disable DB"], "B"),
("System Design", "Database Design", "BCNF prevents?",
 ["Redundancy & anomalies", "Security issues", "SQL injection", "NULL values"], "A"),
("System Design", "Database Design", "Foreign key located in?",
 ["Parent table", "Child table", "Both", "Views only"], "B"),
("System Design", "Database Design", "Which uniquely identifies rows?",
 ["Foreign key", "Primary key", "Index", "Column"], "B"),
("System Design", "Database Design", "OLTP stands for?",
 ["Online Transaction Processing", "Old Transaction Program", "Online Table Processing", "None"], "A"),
("System Design", "Database Design", "DB Partition improves?",
 ["Performance", "Only UI", "Hardware cost", "None"], "A"),



]  # END of list

print("📝 Inserting questions...")

bulk_q = []
for category, topic, question, opts, ans in data:
    bulk_q.append(Question(
        category=category,
        topic=topic,
        question=question,
        option_a=opts[0],
        option_b=opts[1],
        option_c=opts[2],
        option_d=opts[3],
        correct_answer=ans,
        qtype="MCQ"
    ))

Question.objects.bulk_create(bulk_q)

print(f"✔ Successfully inserted {len(bulk_q)} questions 🎯🔥")
print("\nAll done! 🚀")
